modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/TeamFelnull/IamMusicPlayer/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "iammusicplayer"
version = "${version}"
displayName = "Iam Music Player"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/iammusicplayer"
updateJSONURL = "https://raw.githubusercontent.com/TeamFelnull/IamMusicPlayer/master/version_check.json"
authors = "MORIMORI0317, nin8995"
credits = "FelNull developers"
description = '''
Add a boombox that can play music.
The ikisugi music player mod...
'''
logoFile = "logo.png"

[[dependencies.iammusicplayer]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iammusicplayer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iammusicplayer]]
modId = "architectury"
mandatory = true
versionRange = "[13.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.iammusicplayer]]
modId = "cloth_config"
mandatory = true
versionRange = "[16.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iammusicplayer]]
modId = "otyacraftengine"
mandatory = true
versionRange = "[3.7.1-1.21.1-alpha.0,)"
ordering = "NONE"
side = "BOTH"